version: "3"
services:
  jupiter-crypto-postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: jupiter-crypto-postgres
    volumes:
      - jupiter-crypto-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=answersdb
    # restart: unless-stopped

  jupiter-crypto-app:
    image: sci-go:latest
    network_mode: bridge
    container_name: jupiter-crypto-app
    build: .
    expose:
      - 8888
    ports:
      - 8888:8888
    environment:
      - PORT=8888
      - VAULT_ADDR=http://192.168.1.144:8200
      - VAULT_TOKEN=asdf
      - PORT=5000
      - LOG_LEVEL=info
    depends_on:
      - jupiter-crypto-postgres
    links:
      - jupiter-crypto-postgres
volumes:
  jupiter-crypto-data:
