// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/molson82/jupiter/graphql/ent/migrate"

	"github.com/molson82/jupiter/graphql/ent/stonks"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Stonks is the client for interacting with the Stonks builders.
	Stonks *StonksClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Stonks = NewStonksClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Stonks: NewStonksClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		config: cfg,
		Stonks: NewStonksClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Stonks.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Stonks.Use(hooks...)
}

// StonksClient is a client for the Stonks schema.
type StonksClient struct {
	config
}

// NewStonksClient returns a client for the Stonks from the given config.
func NewStonksClient(c config) *StonksClient {
	return &StonksClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `stonks.Hooks(f(g(h())))`.
func (c *StonksClient) Use(hooks ...Hook) {
	c.hooks.Stonks = append(c.hooks.Stonks, hooks...)
}

// Create returns a create builder for Stonks.
func (c *StonksClient) Create() *StonksCreate {
	mutation := newStonksMutation(c.config, OpCreate)
	return &StonksCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Stonks entities.
func (c *StonksClient) CreateBulk(builders ...*StonksCreate) *StonksCreateBulk {
	return &StonksCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Stonks.
func (c *StonksClient) Update() *StonksUpdate {
	mutation := newStonksMutation(c.config, OpUpdate)
	return &StonksUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *StonksClient) UpdateOne(s *Stonks) *StonksUpdateOne {
	mutation := newStonksMutation(c.config, OpUpdateOne, withStonks(s))
	return &StonksUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *StonksClient) UpdateOneID(id int) *StonksUpdateOne {
	mutation := newStonksMutation(c.config, OpUpdateOne, withStonksID(id))
	return &StonksUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Stonks.
func (c *StonksClient) Delete() *StonksDelete {
	mutation := newStonksMutation(c.config, OpDelete)
	return &StonksDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *StonksClient) DeleteOne(s *Stonks) *StonksDeleteOne {
	return c.DeleteOneID(s.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *StonksClient) DeleteOneID(id int) *StonksDeleteOne {
	builder := c.Delete().Where(stonks.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &StonksDeleteOne{builder}
}

// Query returns a query builder for Stonks.
func (c *StonksClient) Query() *StonksQuery {
	return &StonksQuery{
		config: c.config,
	}
}

// Get returns a Stonks entity by its id.
func (c *StonksClient) Get(ctx context.Context, id int) (*Stonks, error) {
	return c.Query().Where(stonks.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *StonksClient) GetX(ctx context.Context, id int) *Stonks {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *StonksClient) Hooks() []Hook {
	return c.hooks.Stonks
}
