// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// StonksColumns holds the columns for the "stonks" table.
	StonksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "symbol", Type: field.TypeString},
		{Name: "price_change", Type: field.TypeString},
	}
	// StonksTable holds the schema information for the "stonks" table.
	StonksTable = &schema.Table{
		Name:        "stonks",
		Columns:     StonksColumns,
		PrimaryKey:  []*schema.Column{StonksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		StonksTable,
	}
)

func init() {
}
