// Code generated by entc, DO NOT EDIT.

package stonks

const (
	// Label holds the string label denoting the stonks type in the database.
	Label = "stonks"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSymbol holds the string denoting the symbol field in the database.
	FieldSymbol = "symbol"
	// FieldPriceChange holds the string denoting the pricechange field in the database.
	FieldPriceChange = "price_change"
	// Table holds the table name of the stonks in the database.
	Table = "stonks"
)

// Columns holds all SQL columns for stonks fields.
var Columns = []string{
	FieldID,
	FieldSymbol,
	FieldPriceChange,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
